### ISSUE TITLE
gs4 authentication issue with rstudio.reed.edu

### ISSUE THREAD

**Issue by RhoBott** [RhoBott/data_at_reed#44]
Need to adjust `googlesheets4` documentation to reflect the necessary _gargling_ of _oobs_ 

For more (and less) nonsense + backstory, see [thread in mLabbies](https://reed-cis.slack.com/archives/C0552T9H2/p1613408416005600)

**Comment by joshyam-k** [comment]
wrapping this up after merging Leilas PR!
