### ISSUE TITLE
add to pages: lubridate 

### ISSUE THREAD

**Issue by RhoBott** [RhoBott/data_at_reed#48]
Time data is notoriously complicated + variably formatted; `lubridate` is _great_ at dealing with it, and also -- folks who are using our pages as their springboard to R might not know this exists.

I'm not sure where in our documentation this fits _or_ entirely how to scope this; adding here to start the conversation.

Some things we might wish to add: 
- link to a cheatsheet
- clear instructions on loading (it's part of The Tidyverse, but is it part of library(tidyverse)?)
- worked examples of a couple of functions that seem relevant to student/faculty work ((Main use that comes to mind for me is matching GPS/time data with environmental chemistry/time data; can share the most recent iteration of this w/ folks who are curious))
- surely other things; this is a start!

**Comment by simonpcouch** [comment]
Totally on board for having something re: lubridate around. 

One observation which may not hold for others... I mostly use `lubridate` when I'm plotting---getting axes to format properly / trying to extract more or less discrete units of time to visualize. Is this others' experience? If so, maybe a home for brief mention + explanation could be in the plotting sections. If not so, ignore. :-)
