### ISSUE TITLE
scope question: functions and things

### ISSUE THREAD

**Issue by simonpcouch** [RhoBott/data_at_reed#49]
Is _doing things many times in R_ within the scope of this documentation? Mostly thinking about writing functions and iterating with `purrr`. From my understanding, this is not a component of intro stats but is a component of data science (as in MATH 241). not sure if this happens in other courses at reed, though i feel like i've seen some bio courses do this type of stuff as needed.

**Comment by RhoBott** [comment]
First thought: If you think something would be potentially useful to add to this documentation, let's get it on the list. (Ye olde "trust your gut/instincts" -- if it feels [in this case, important], you're probably right.)

I can imagine applications of these sort of iterative approaches (maybe add in a `for`, an `apply`...) for students + faculty doing research as well as coursework.

Or, TL/DR: upvote + support!

**Comment by simonpcouch** [comment]
Aaaand just chatted with kbott here briefly. Answer for now: sit tight on full-on documentation but drop a short note + link out somewhere in the existing pages.

Main drawbacks to full thing, for posterity: need to dip out of tidyverse for vectors vs lists vs data frames, and keeping things within confines of tidy might be best for maintainability.
