### ISSUE TITLE
using `gt` in the summary tables document

### ISSUE THREAD

**Issue by simonpcouch** [RhoBott/data_at_reed#50]
Should we mention/teach `gt` ("Grammar of Tables") in the Summary Tables document? Or elsewhere?

`gt` is a package for making tables with a principled (+ "tidy") grammar. The package is hot off the presses (~8 months old?) from RStudio folks, and is thus not very widely used. Kelly is already teaching with it in data science, and given its institutional backing, I'd guess that it will only get more popular with time.

I haven't used the package before, but @joshyam-k just learned it in 241. Any thoughts?

**Comment by joshyam-k** [comment]
oops sorry just saw this, I think `gt` could be a cool addition. I can definitely see it being something that gets really popular really soon. In fact just while Kelly was teaching the section lots of people mentioned wanting to use it in their thesis.

in any case I think some documentation on it could definitely be a good idea!

**Comment by joshyam-k** [comment]
I think this is wrapped up, so I'm closing it for now!
