### ISSUE TITLE
content addition: troubleshooting tips

### ISSUE THREAD

**Issue by shokatl** [RhoBott/data_at_reed#52]
We all have little tips and tricks for how we troubleshoot code when it isn't doing what we want it to do, maybe we should have a little section with some of these tips? some ideas:

- How to access help files using the console (`?function_name`)
- How (and why) to check the class of a variable (`class(dataset$var)`)
- Running code line by line and checking the state of your data at each step to see where the error is originating

Would love to hear other ideas or whether you all think this is necessary?

**Comment by zolli22** [comment]
I *love* this idea! 

on top of checking the class/type of a variable, perhaps the very basics of `as.numeric` or `as.character`? 
things with factors/dates would be more complicated, and in other potential sections on `forcats` and `lubridate`. 

maybe: a list of go-to things to try if a document isn't knitting? ie: 
- double check all your packages! make sure everything is loaded
- double check variable names and data frame names
- [and more]

**Comment by simonpcouch** [comment]
All for this. :-) 

Maybe something about keeping an eye out for `NA`s? `na.rm = TRUE`?

**Comment by joshyam-k** [comment]
If people feel good about this I think we can close this issue!

**Comment by zolli22** [comment]
I think it's great! 

any last comments/thoughts before we close this @simonpcouch @RhoBott ?

**Comment by simonpcouch** [comment]
Looks great. :-)
