### ISSUE TITLE
add short desc regarding dataset choice

### ISSUE THREAD

**Issue by joshyam-k** [RhoBott/data_at_reed#67]
Inside of our introduction of the `palmerpenguins` dataset include a sentence along the lines of:

"For more on why not iris, here's a post from [link to the lady who originally wrote the thing])"

Even though `palmerpenguins` is awesome it could be good to offer some insight into why we chose it over the other commonly used demo datasets. Probably best to keep this short and simple.

**Comment by shokatl** [comment]
Think Ingrid did a great job of keeping it short and sweet! :)
