### ISSUE TITLE
Internal links!

### ISSUE THREAD

**Issue by shokatl** [RhoBott/data_at_reed#71]
Thinking about if we want to change current internal links to include the new advanced wrangling doc, the refactoring doc, and the troubleshooting doc

**Comment by joshyam-k** [comment]
I think this is a good idea, So we don't forget, I'll note here that kbott added a section under "working with categories using formats" on the advanced wrangling rmd with a spot for a link to our page on refactoring levels in plots.

**Comment by joshyam-k** [comment]
Ingrid and I have wrapped with up!
