### ISSUE TITLE
intro / loading data into rstudio.reed.edu

### ISSUE THREAD

**Issue by RhoBott** [RhoBott/data_at_reed#76]
Under "[Uploading data to the Reed Rstudio server](https://github.com/RhoBott/data_at_reed/blob/main/01-getting-started/reed_rstudio_server.Rmd)" the page currently reads:

> You can now load the data into R in the same way you would if you were working with data stored on your computer with the desktop version of R. See our [loading data](https://www.reed.edu/data-at-reed/resources/R/from-a-.csv.html) page for more information.

Two questions:
1. do you think that is sufficiently clear as an explanation _for this page_
2. is the information on the linked page sufficiently clear, imagining a naive/novice user?

Take a look + discuss below, I'll review inputs end of day on Tuesday 2021/10/26.

**Comment by RhoBott** [comment]
@zolli22 can you pick this up + draft some proposed edits?

**Comment by RhoBott** [comment]
... and suddenly _we are talking about a whole new page with a wealth of additional information!_ this is exciting; i am absolutely all for complete documentation.

i am also a huge fan of small steps and iterating (any other devotees of the [stepwise mutation model](https://en.wikipedia.org/wiki/Stepwise_mutation_model)? ... no? ... right. population genetics nerd... i digress)

so! proposal here:
while we work out what a big content add + partial restructuring looks like (#82 ), i would like to have what i think could be a _fairly minor edit_ made to the _loading data pages that describes to people how to load data onto the server. 

imagine that your audience is completely new here, and has been told to take a CSV and use it on rstudio.reed.edu -- -- give them the information that they need to do that. (1. upload file to rstudio.reed.edu (specifics) 2. import into environment (specifics) 3. (anything else relevant?) 4. success!)

ingrid has started this (see commit above)!

going to kick this _small add to the loading pages_ to a combo of @zolli22 and @avawillis based on this week's shifts, and then we _as a team_ can continue noodling on the larger issue #82

**Comment by joshyam-k** [comment]
closing for now
