### ISSUE TITLE
rvest and robots and confused kbott, oh my!

### ISSUE THREAD

**Issue by RhoBott** [RhoBott/data_at_reed#77]
the current version of our walking folks through how to [scrape + bring in data ](https://github.com/RhoBott/data_at_reed/blob/main/02-loading-data/from_internet.Rmd )has me ... _confused_. (for ease of reading, [public-facing page](https://www.reed.edu/data-at-reed/resources/R/from-internet.html) )

points of confusion include:
1. do we mean to recommend this robotstxt business? (if so, this is news to me, but ... neat?)
2. if we _do_ intend to (1), i _think_ we may need to clarify / rework this text a bit
3. if we do _not_ intend to (1), neat! deleting is easy; i wanted to confer before making anything Go Away

again -- comments fr all here by end of day Tuesday 2021/10/26, please + thank you + high-five.

**Comment by RhoBott** [comment]
@joshyam-k / @zolli22 could you take a look at this Tuesday (2021/11/02) if/when you have a minute, and then have later-in-the-day folks (@zolli22 / @avawillis ) be a second set of eyes ... at which point we can add that updated text to what @avawillis and @anaqb will be working on, perhaps, next week?

@avawillis I am not anti-visual aids - maybe that's a new issue / goes on a Future Selves wishlist? (I think we'll always be tweaking these pages, as is the way of Proper Living Documentation...?)

(( this comment brought to you by excessive at-ing ))

**Comment by joshyam-k** [comment]
just opened a Pull-request for this! We can all work inside of this PR by

1. opening the data_at_reed project in your rstudio install
2. "pull"-ing to make sure your local project is up to date
3. going to the section In the rstudio interface with "Environment" "History" "Connections" etc and clicking on 'main' which should be next to "New Branch" (this should be In the top right hand corner of the pane)
4. selecting "ro(bott)s-and-rvest" 
5. making changes inside of `02/loading-data/from_internet.Rmd`
6. commit, push, done!


Let me know if you have any questions about all of this : -)
